resources:
  - namespace.yml
  - service.yml
  - deployment.yml
  - ingress.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: image
    newName: aaa
    newTag: latest
